### ISSUE TITLE
Incompatibility with Railcraft

### ISSUE THREAD

**Issue by vpontin** [Uristqwerty/CraftGuide#18]
Hi!

I'm having issues with craftguide and railcraft (https://github.com/CovertJaguar/Railcraft/).

After installing railcraft, the item list shows a "null" block first, and the search box don't work anymore.

![image](https://cloud.githubusercontent.com/assets/3485505/9445101/b5914b2c-4a60-11e5-8e2b-3c9e1e1cb181.png)

Removed railcraft, everything runs fine. No errors appears in log. It don't crash the game, but is very annoying.

Is there a way to fix this in your side?

**Comment by Uristqwerty** [comment]
I wasn't able to reproduce the effect (maybe it's interaction with some other mods, or a configuration change, or I tried with the wrong versions), so all I could do was change one possible thing so that hopefully it can search even with null items.

Does http://minecraft.curseforge.com/mc-mods/75557-craftguide/files/2255897 work?

**Comment by Aleszp** [comment]
Unfortunately still doesn't help (at least for me). The last non-bugged version is 1.6.8.1 (and I'm gonna stick to it until there's solution). In 1.6.8.2 bug occured first time. Currently using Forge 10.13.4.1448 (reccomended build), I don't remember which previous versions of forge I used, but it's seems to be connected not only with railcraft. (Removing it didn't solve the problem in 1.6.9.0).

To help find problem turned on craftguides excessive theme logging (don't know, maybe there's some clue).

Below craftguide.log: 
```
CraftGuide: Extracting 'base/base.png' to '/home/aleksander/.minecraftAlt/config/CraftGuide/themes/base/base.png'
CraftGuide: Extracting 'base/readme.txt' to '/home/aleksander/.minecraftAlt/config/CraftGuide/themes/base/readme.txt'
CraftGuide: Extracting 'base/theme.xml' to '/home/aleksander/.minecraftAlt/config/CraftGuide/themes/base/theme.xml'
CraftGuide: Extracting 'dark/dark.png' to '/home/aleksander/.minecraftAlt/config/CraftGuide/themes/dark/dark.png'
CraftGuide: Extracting 'dark/dark_brew.png' to '/home/aleksander/.minecraftAlt/config/CraftGuide/themes/dark/dark_brew.png'
CraftGuide: Extracting 'dark/dark_craft.png' to '/home/aleksander/.minecraftAlt/config/CraftGuide/themes/dark/dark_craft.png'
CraftGuide: Extracting 'dark/theme.xml' to '/home/aleksander/.minecraftAlt/config/CraftGuide/themes/dark/theme.xml'
CraftGuide: Extracting 'texpack_support/theme.xml' to '/home/aleksander/.minecraftAlt/config/CraftGuide/themes/texpack_support/theme.xml'
(re)loading themes...
  Trying to load directory: texpack_support
    Found theme.xml
    Loaded texpack_support
  Trying to load directory: base
    Found theme.xml
    Loaded base
  Trying to load directory: dark
    Found theme.xml
    Loaded dark
Validating themes:
  Looping over unvalidated themes:
    Theme 'base_texpack':
      Checking dependencies...
        Dependency 'theme_base'
    Theme 'theme_base':
      Checking dependencies...
      All dependencies processed without error. Validating theme...
      Checking image sources for image 'base_image'
        Source '[Ljava.lang.Object;@424f2dc8'
          Checking if image exists and is valid...
            Checking theme location for 'base.png'
      Checking image sources for image 'brew_recipe_background'
        Source '[Ljava.lang.Object;@154034c1'
          Checking if image exists and is valid...
            Searching resource packs, Minecraft.jar, and mod jars/zips/dirs for 'craftguide:textures/gui/BrewGuide.png'
              Found.
      Checking image sources for image 'recipe_backgrounds'
        Source '[Ljava.lang.Object;@61a456ce'
          Checking if image exists and is valid...
            Searching resource packs, Minecraft.jar, and mod jars/zips/dirs for 'craftguide:textures/gui/CraftGuideRecipe.png'
              Found.
    Theme 'dark':
      Checking dependencies...
        Dependency 'theme_base'
  1 themes validated
  Looping over unvalidated themes:
    Theme 'base_texpack':
      Checking dependencies...
        Dependency 'theme_base'
      All dependencies processed without error. Validating theme...
      Checking image sources for image 'base_image'
        Source '[Ljava.lang.Object;@4eccd7e5'
          Checking if image exists and is valid...
            Searching resource packs, Minecraft.jar, and mod jars/zips/dirs for 'craftguide:textures/gui/CraftGuide.png'
              Found.
    Theme 'dark':
      Checking dependencies...
        Dependency 'theme_base'
      All dependencies processed without error. Validating theme...
      Checking image sources for image 'base_image'
        Source '[Ljava.lang.Object;@1670f93f'
          Checking if image exists and is valid...
            Checking theme location for 'dark.png'
      Checking image sources for image 'brew_recipe_background'
        Source '[Ljava.lang.Object;@3cd68940'
          Checking if image exists and is valid...
            Checking theme location for 'dark_brew.png'
      Checking image sources for image 'recipe_backgrounds'
        Source '[Ljava.lang.Object;@140d12c0'
          Checking if image exists and is valid...
            Checking theme location for 'dark_craft.png'
  2 themes validated
Result:
  'base_texpack' loaded successfully
  'theme_base' loaded successfully
  'dark' loaded successfully
Building theme 'base_texpack':
  Merging...
    Handling dependencies:
      Dependency 'theme_base'
        Not merged yet. Merging... [
    Handling dependencies:
    Merging:
      Not already merged. adding images and textures.
        ] finished merging 'theme_base'
    Merging:
      Not already merged. adding images and textures.
  Generating textures...
    Loading image 'base_image'
      Loading resource image 'craftguide:textures/gui/CraftGuide.png'
    Loading image 'brew_recipe_background'
      Loading resource image 'craftguide:textures/gui/BrewGuide.png'
    Loading image 'recipe_backgrounds'
      Loading resource image 'craftguide:textures/gui/CraftGuideRecipe.png'
    Adding texture 'toggle_on'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@2a97f9a3'
    Adding texture 'liquidFilterContainer'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@359a6a1'
    Adding texture 'toggle_on_over'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@7e655354'
    Adding texture 'type-tab_icon'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@2b15fbb5'
    Adding texture 'stack-any'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@3e5a5595'
    Adding texture 'filter-add'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@70f88051'
    Adding texture 'toggle_off_over'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@24d382e9'
    Adding texture 'button_down'. Maps to 'uristqwerty.gui_craftguide.texture.BorderedTexture@201f0d95'
    Adding texture 'pane'. Maps to 'uristqwerty.gui_craftguide.texture.BorderedTexture@4c8512fe'
    Adding texture 'button_over'. Maps to 'uristqwerty.gui_craftguide.texture.BorderedTexture@78cbf937'
    Adding texture 'stack-background'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@4037f80d'
    Adding texture 'stack-oredict'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@181c263b'
    Adding texture 'text-filter'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@7cead524'
    Adding texture 'brew_recipe_background'. Maps to 'uristqwerty.gui_craftguide.minecraft.Image@5bcf89cf'
    Adding texture 'filter-remove'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@24c7f52b'
    Adding texture 'stack-oredict-single'. Maps to 'uristqwerty.gui_craftguide.texture.TintedTexture@5d132276'
    Adding texture 'config-tab_icon'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@77fa8f05'
    Adding texture 'recipe_backgrounds'. Maps to 'uristqwerty.gui_craftguide.minecraft.Image@50dcf1c4'
    Adding texture 'toggle_off'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@4ba92859'
    Adding texture 'EU-icon'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@feda3c8'
    Adding texture 'base_image'. Maps to 'uristqwerty.gui_craftguide.minecraft.Image@2ccc9797'
    Adding texture 'button_up'. Maps to 'uristqwerty.gui_craftguide.texture.BorderedTexture@1ba9111b'
    Adding texture 'window'. Maps to 'uristqwerty.gui_craftguide.texture.BorderedTexture@19c019d7'
    Adding texture 'recipe-tab_icon'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@7bd11ac4'
    Adding texture 'item_error'. Maps to 'uristqwerty.gui_craftguide.texture.TextureClip@33e94a06'
(re)loading recipe list...
  Getting recipes...
    Generating recipes from uristqwerty.CraftGuide.recipes.DefaultRecipeProvider
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at uristqwerty.CraftGuide.recipes.DefaultRecipeProvider.addFurnaceRecipes(DefaultRecipeProvider.java:162)
	at uristqwerty.CraftGuide.recipes.DefaultRecipeProvider.generateRecipes(DefaultRecipeProvider.java:152)
	at uristqwerty.CraftGuide.RecipeCache.generateRecipes(RecipeCache.java:259)
	at uristqwerty.CraftGuide.RecipeCache.reset(RecipeCache.java:50)
	at uristqwerty.CraftGuide.RecipeCache.<init>(RecipeCache.java:42)
	at uristqwerty.CraftGuide.GuiCraftGuide.<init>(GuiCraftGuide.java:42)
	at uristqwerty.CraftGuide.GuiCraftGuide.getInstance(GuiCraftGuide.java:65)
	at uristqwerty.CraftGuide.client.fml.CraftGuideClient_FML.openGUI(CraftGuideClient_FML.java:109)
	at uristqwerty.CraftGuide.client.fml.CraftGuideClient_FML.checkKeybind(CraftGuideClient_FML.java:46)
	at uristqwerty.CraftGuide.CraftGuide_FML$KeyCheckTick.clientTick(CraftGuide_FML.java:36)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_89_KeyCheckTick_clientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    Generating recipes from uristqwerty.CraftGuide.recipes.BrewingRecipes
    Generating recipes from uristqwerty.CraftGuide.recipes.IC2ExperimentalRecipes
    Generating recipes from uristqwerty.CraftGuide.recipes.BuildCraftRecipes
java.lang.NoClassDefFoundError: buildcraft/api/recipes/BuildcraftRecipes
	at uristqwerty.CraftGuide.recipes.BuildCraftRecipes.addAssemblyRecipes(BuildCraftRecipes.java:75)
	at uristqwerty.CraftGuide.recipes.BuildCraftRecipes.generateRecipes(BuildCraftRecipes.java:37)
	at uristqwerty.CraftGuide.RecipeCache.generateRecipes(RecipeCache.java:259)
	at uristqwerty.CraftGuide.RecipeCache.reset(RecipeCache.java:50)
	at uristqwerty.CraftGuide.RecipeCache.<init>(RecipeCache.java:42)
	at uristqwerty.CraftGuide.GuiCraftGuide.<init>(GuiCraftGuide.java:42)
	at uristqwerty.CraftGuide.GuiCraftGuide.getInstance(GuiCraftGuide.java:65)
	at uristqwerty.CraftGuide.client.fml.CraftGuideClient_FML.openGUI(CraftGuideClient_FML.java:109)
	at uristqwerty.CraftGuide.client.fml.CraftGuideClient_FML.checkKeybind(CraftGuideClient_FML.java:46)
	at uristqwerty.CraftGuide.CraftGuide_FML$KeyCheckTick.clientTick(CraftGuide_FML.java:36)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_89_KeyCheckTick_clientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: buildcraft.api.recipes.BuildcraftRecipes
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
Caused by: java.lang.NullPointerException
    Generating recipes from mods.railcraft.common.plugins.craftguide.BlastFurnacePlugin
    Generating recipes from mods.railcraft.common.plugins.craftguide.CokeOvenPlugin
    Generating recipes from mods.railcraft.common.plugins.craftguide.RockCrusherPlugin
    Generating recipes from mods.railcraft.common.plugins.craftguide.RollingMachinePlugin
    Generating recipes from mods.railcraft.common.plugins.craftguide.CustomRecipesPlugin
  Filtering recipes...
    Filtering recipes from mods.railcraft.common.plugins.craftguide.RecipeFilter
Failed to render ItemStack {itemID = null, itemDamage = 0, stackSize = 1} (Further stack traces from this particular ItemStack instance will not be logged)
net.minecraft.util.ReportedException: Rendering item
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:604)
	at uristqwerty.CraftGuide.client.ui.GuiRenderer.renderItem(GuiRenderer.java:256)
	at uristqwerty.CraftGuide.client.ui.GuiRenderer.drawItemStack(GuiRenderer.java:212)
	at uristqwerty.CraftGuide.client.ui.GuiRenderer.drawItemStack(GuiRenderer.java:196)
	at uristqwerty.CraftGuide.client.ui.FilterSelectGrid.renderGridCell(FilterSelectGrid.java:147)
	at uristqwerty.CraftGuide.client.ui.GuiScrollableGrid.renderGridRow(GuiScrollableGrid.java:260)
	at uristqwerty.CraftGuide.client.ui.GuiScrollableGrid.renderGridRows(GuiScrollableGrid.java:249)
	at uristqwerty.CraftGuide.client.ui.Rendering.GridRect.render(GridRect.java:29)
	at uristqwerty.CraftGuide.client.ui.Rendering.GridRect.render(GridRect.java:40)
	at uristqwerty.CraftGuide.client.ui.GuiRenderer.render(GuiRenderer.java:81)
	at uristqwerty.gui_craftguide.components.Window.render(Window.java:53)
	at uristqwerty.gui_craftguide.components.GuiElement.render(GuiElement.java:252)
	at uristqwerty.gui_craftguide.components.GuiElement.render(GuiElement.java:252)
	at uristqwerty.gui_craftguide.components.GuiElement.render(GuiElement.java:252)
	at uristqwerty.gui_craftguide.components.GuiElement.render(GuiElement.java:252)
	at uristqwerty.gui_craftguide.components.GuiElement.render(GuiElement.java:252)
	at uristqwerty.gui_craftguide.components.GuiElement.render(GuiElement.java:252)
	at uristqwerty.gui_craftguide.components.GuiElement.render(GuiElement.java:237)
	at uristqwerty.CraftGuide.client.ui.GuiScrollableGrid.draw(GuiScrollableGrid.java:55)
	at uristqwerty.CraftGuide.client.ui.FilterSelectGrid.draw(FilterSelectGrid.java:192)
	at uristqwerty.gui_craftguide.components.GuiElement.drawChildren(GuiElement.java:187)
	at uristqwerty.gui_craftguide.components.GuiElement.draw(GuiElement.java:180)
	at uristqwerty.gui_craftguide.components.GuiElement.drawChildren(GuiElement.java:187)
	at uristqwerty.gui_craftguide.components.GuiElement.draw(GuiElement.java:180)
	at uristqwerty.gui_craftguide.components.GuiElement.drawChildren(GuiElement.java:187)
	at uristqwerty.gui_craftguide.components.GuiElement.draw(GuiElement.java:180)
	at uristqwerty.gui_craftguide.components.GuiElement.drawChildren(GuiElement.java:187)
	at uristqwerty.gui_craftguide.components.GuiElement.draw(GuiElement.java:180)
	at uristqwerty.gui_craftguide.components.GuiElement.drawChildren(GuiElement.java:187)
	at uristqwerty.gui_craftguide.components.GuiElement.draw(GuiElement.java:180)
	at uristqwerty.gui_craftguide.components.Window.draw(Window.java:106)
	at uristqwerty.gui_craftguide.minecraft.Gui.func_73863_a(Gui.java:41)
	at uristqwerty.CraftGuide.GuiCraftGuide.func_73863_a(GuiCraftGuide.java:431)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:402)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	... 42 more
```

By the way (as I'm commenting this mod): Man, big thanks for CraftGuide :D, you did great job coding it :).
